import { TechniqueTemplate } from '../types';

export const TECHNIQUES: TechniqueTemplate[] = [
  {
    id: 'saute',
    name: 'Sauté & pan sauce',
    requiredRoles: ['protein', 'fat', 'aromatic'],
    optionalRoles: ['acid', 'spice'],
    baseMinutes: 20,
    minutesPerExtraIngredient: 2,
    difficulty: 1,
    steps: (ctx) => [
      `Season ${ctx.protein ?? 'your protein'} and pat dry.`,
      `Heat ${ctx.fat ?? 'oil'} in a pan over medium-high heat.`,
      `Sear the ${ctx.protein ?? 'protein'} until browned, then set aside.`,
      `In the same pan, sauté ${ctx.aromatics.join(', ') || 'aromatics'} until fragrant.`,
      ctx.acid ? `Deglaze with ${ctx.acid} to build a pan sauce.` : 'Add a splash of water or stock to lift the fond.',
      `Return the ${ctx.protein ?? 'protein'} to the pan, toss with the sauce, and finish with ${ctx.spices.join(', ') || 'seasoning'}.`,
    ],
  },
  {
    id: 'roast',
    name: 'Sheet-pan roast',
    requiredRoles: ['protein', 'vegetable', 'fat'],
    optionalRoles: ['spice', 'starch'],
    baseMinutes: 40,
    minutesPerExtraIngredient: 3,
    difficulty: 1,
    steps: (ctx) => [
      'Preheat oven to 425°F (220°C).',
      `Toss ${ctx.protein ?? 'protein'} and ${ctx.vegetables.join(', ') || 'vegetables'} with ${ctx.fat ?? 'oil'} and ${ctx.spices.join(', ') || 'seasoning'}.`,
      'Spread in a single layer on a sheet pan.',
      'Roast until the protein is cooked through and vegetables are caramelized, 25-35 min.',
    ],
  },
  {
    id: 'braise',
    name: 'Braise',
    requiredRoles: ['protein', 'liquid', 'aromatic'],
    optionalRoles: ['acid', 'vegetable'],
    baseMinutes: 90,
    minutesPerExtraIngredient: 4,
    difficulty: 2,
    steps: (ctx) => [
      `Sear ${ctx.protein ?? 'protein'} on all sides, then remove.`,
      `Sauté ${ctx.aromatics.join(', ') || 'aromatics'} in the same pot.`,
      `Return protein, add enough liquid to come halfway up, plus ${ctx.acid ?? 'an acid'} for brightness.`,
      'Cover and simmer low until fork-tender.',
    ],
  },
  {
    id: 'stir-fry',
    name: 'Stir-fry',
    requiredRoles: ['protein', 'vegetable', 'aromatic'],
    optionalRoles: ['starch', 'spice'],
    baseMinutes: 20,
    minutesPerExtraIngredient: 2,
    difficulty: 2,
    steps: (ctx) => [
      'Have all ingredients prepped before you start — this moves fast.',
      `Sear ${ctx.protein ?? 'protein'} in a very hot wok/pan, then remove.`,
      `Stir-fry ${ctx.aromatics.join(', ') || 'aromatics'} for 30 seconds.`,
      `Add ${ctx.vegetables.join(', ') || 'vegetables'} and stir-fry until crisp-tender.`,
      `Return protein, toss with ${ctx.spices.join(', ') || 'sauce'}, serve over ${ctx.starch ?? 'rice'}.`,
    ],
  },
  {
    id: 'raw-salad',
    name: 'Composed salad',
    requiredRoles: ['vegetable', 'fat', 'acid'],
    optionalRoles: ['protein', 'dairy'],
    baseMinutes: 10,
    minutesPerExtraIngredient: 1,
    difficulty: 1,
    steps: (ctx) => [
      `Whisk ${ctx.fat ?? 'oil'} and ${ctx.acid ?? 'acid'} into a vinaigrette.`,
      `Combine ${ctx.vegetables.join(', ') || 'vegetables'}${ctx.protein ? ` with ${ctx.protein}` : ''}.`,
      'Dress just before serving and season to taste.',
    ],
  },
  {
    id: 'simmer-soup',
    name: 'Simmer soup',
    requiredRoles: ['liquid', 'aromatic', 'vegetable'],
    optionalRoles: ['protein', 'starch'],
    baseMinutes: 35,
    minutesPerExtraIngredient: 3,
    difficulty: 1,
    steps: (ctx) => [
      `Sauté ${ctx.aromatics.join(', ') || 'aromatics'} until soft.`,
      `Add ${ctx.vegetables.join(', ') || 'vegetables'}${ctx.protein ? ` and ${ctx.protein}` : ''}, then cover with liquid.`,
      'Simmer until everything is tender, 20-25 min.',
      'Adjust seasoning and serve.',
    ],
  },
  {
    id: 'grill',
    name: 'Grill/sear',
    requiredRoles: ['protein', 'fat'],
    optionalRoles: ['acid', 'spice', 'vegetable'],
    baseMinutes: 20,
    minutesPerExtraIngredient: 2,
    difficulty: 1,
    steps: (ctx) => [
      `Marinate ${ctx.protein ?? 'protein'} briefly in ${ctx.fat ?? 'oil'}${ctx.acid ? ` and ${ctx.acid}` : ''} with ${ctx.spices.join(', ') || 'seasoning'}.`,
      'Grill or pan-sear over high heat to a good crust.',
      'Rest 5 minutes before slicing.',
    ],
  },
];
