import { TechniqueTemplate } from '../types';

export const TECHNIQUES: TechniqueTemplate[] = [
  {
    id: 'saute',
    name: 'Sauté & pan sauce',
    requiredRoles: ['protein', 'fat', 'aromatic'],
    optionalRoles: ['acid', 'spice'],
    baseMinutes: 20,
    minutesPerExtraIngredient: 2,
    difficulty: 1,
    healthModifier: 0.95,
    steps: (ctx) => [
      `Season ${ctx.protein ?? 'your protein'} and pat dry.`,
      `Heat ${ctx.fat ?? 'oil'} in a pan over medium-high heat.`,
      `Sear the ${ctx.protein ?? 'protein'} until browned, then set aside.`,
      `In the same pan, sauté ${ctx.aromatics.join(', ') || 'aromatics'} until fragrant.`,
      ctx.acid ? `Deglaze with ${ctx.acid} to build a pan sauce.` : 'Add a splash of water or stock to lift the fond.',
      `Return the ${ctx.protein ?? 'protein'} to the pan, toss with the sauce, and finish with ${ctx.spices.join(', ') || 'seasoning'}.`,
    ],
  },
  {
    id: 'roast',
    name: 'Sheet-pan roast',
    requiredRoles: ['protein', 'vegetable', 'fat'],
    optionalRoles: ['spice', 'starch'],
    baseMinutes: 40,
    minutesPerExtraIngredient: 3,
    difficulty: 1,
    healthModifier: 1.0,
    steps: (ctx) => [
      'Preheat oven to 425°F (220°C).',
      `Toss ${ctx.protein ?? 'protein'} and ${ctx.vegetables.join(', ') || 'vegetables'} with ${ctx.fat ?? 'oil'} and ${ctx.spices.join(', ') || 'seasoning'}.`,
      'Spread in a single layer on a sheet pan.',
      'Roast until the protein is cooked through and vegetables are caramelized, 25-35 min.',
    ],
  },
  {
    id: 'braise',
    name: 'Braise',
    requiredRoles: ['protein', 'liquid', 'aromatic'],
    optionalRoles: ['acid', 'vegetable'],
    baseMinutes: 90,
    minutesPerExtraIngredient: 4,
    difficulty: 2,
    healthModifier: 0.95,
    steps: (ctx) => [
      `Sear ${ctx.protein ?? 'protein'} on all sides, then remove.`,
      `Sauté ${ctx.aromatics.join(', ') || 'aromatics'} in the same pot.`,
      `Return protein, add enough liquid to come halfway up, plus ${ctx.acid ?? 'an acid'} for brightness.`,
      'Cover and simmer low until fork-tender.',
    ],
  },
  {
    id: 'stir-fry',
    name: 'Stir-fry',
    requiredRoles: ['protein', 'vegetable', 'aromatic'],
    optionalRoles: ['starch', 'spice'],
    baseMinutes: 20,
    minutesPerExtraIngredient: 2,
    difficulty: 2,
    healthModifier: 0.95,
    steps: (ctx) => [
      'Have all ingredients prepped before you start — this moves fast.',
      `Sear ${ctx.protein ?? 'protein'} in a very hot wok/pan, then remove.`,
      `Stir-fry ${ctx.aromatics.join(', ') || 'aromatics'} for 30 seconds.`,
      `Add ${ctx.vegetables.join(', ') || 'vegetables'} and stir-fry until crisp-tender.`,
      `Return protein, toss with ${ctx.spices.join(', ') || 'sauce'}, serve over ${ctx.starch ?? 'rice'}.`,
    ],
  },
  {
    id: 'raw-salad',
    name: 'Composed salad',
    requiredRoles: ['vegetable', 'fat', 'acid'],
    optionalRoles: ['protein', 'dairy'],
    baseMinutes: 10,
    minutesPerExtraIngredient: 1,
    difficulty: 1,
    healthModifier: 1.1,
    steps: (ctx) => [
      `Whisk ${ctx.fat ?? 'oil'} and ${ctx.acid ?? 'acid'} into a vinaigrette.`,
      `Combine ${ctx.vegetables.join(', ') || 'vegetables'}${ctx.protein ? ` with ${ctx.protein}` : ''}.`,
      'Dress just before serving and season to taste.',
    ],
  },
  {
    id: 'simmer-soup',
    name: 'Simmer soup',
    requiredRoles: ['liquid', 'aromatic', 'vegetable'],
    optionalRoles: ['protein', 'starch'],
    baseMinutes: 35,
    minutesPerExtraIngredient: 3,
    difficulty: 1,
    healthModifier: 1.0,
    steps: (ctx) => [
      `Sauté ${ctx.aromatics.join(', ') || 'aromatics'} until soft.`,
      `Add ${ctx.vegetables.join(', ') || 'vegetables'}${ctx.protein ? ` and ${ctx.protein}` : ''}, then cover with liquid.`,
      'Simmer until everything is tender, 20-25 min.',
      'Adjust seasoning and serve.',
    ],
  },
  {
    id: 'grill',
    name: 'Grill/sear',
    requiredRoles: ['protein', 'fat'],
    optionalRoles: ['acid', 'spice', 'vegetable'],
    baseMinutes: 20,
    minutesPerExtraIngredient: 2,
    difficulty: 1,
    healthModifier: 1.0,
    steps: (ctx) => [
      `Marinate ${ctx.protein ?? 'protein'} briefly in ${ctx.fat ?? 'oil'}${ctx.acid ? ` and ${ctx.acid}` : ''} with ${ctx.spices.join(', ') || 'seasoning'}.`,
      'Grill or pan-sear over high heat to a good crust.',
      'Rest 5 minutes before slicing.',
    ],
  },
  {
    id: 'bake',
    name: 'Baked casserole/gratin',
    requiredRoles: ['starch', 'dairy'],
    optionalRoles: ['protein', 'vegetable', 'spice'],
    baseMinutes: 45,
    minutesPerExtraIngredient: 3,
    difficulty: 2,
    healthModifier: 0.9,
    steps: (ctx) => [
      'Preheat oven to 375°F (190°C).',
      `Layer ${ctx.starch ?? 'starch'}${ctx.protein ? ` and ${ctx.protein}` : ''} with ${ctx.vegetables.join(', ') || 'vegetables'} in a baking dish.`,
      `Top with ${ctx.dairy ?? 'cheese'} and ${ctx.spices.join(', ') || 'seasoning'}.`,
      'Bake until bubbling and golden on top, about 30 min.',
    ],
  },
  {
    id: 'steam',
    name: 'Steamed',
    requiredRoles: ['vegetable'],
    optionalRoles: ['protein', 'spice', 'acid'],
    baseMinutes: 15,
    minutesPerExtraIngredient: 2,
    difficulty: 1,
    healthModifier: 1.15,
    steps: (ctx) => [
      `Bring water to a boil in a steamer pot.`,
      `Steam ${ctx.vegetables.join(', ') || 'vegetables'}${ctx.protein ? ` and ${ctx.protein}` : ''} until just tender.`,
      `Finish with ${ctx.acid ?? 'a squeeze of citrus'} and ${ctx.spices.join(', ') || 'seasoning'}.`,
    ],
  },
  {
    id: 'poach',
    name: 'Poached',
    requiredRoles: ['protein', 'liquid'],
    optionalRoles: ['acid', 'aromatic'],
    baseMinutes: 20,
    minutesPerExtraIngredient: 2,
    difficulty: 2,
    healthModifier: 1.05,
    steps: (ctx) => [
      `Bring ${ctx.protein ? 'a pot of liquid' : 'liquid'} to a gentle simmer with ${ctx.aromatics.join(', ') || 'aromatics'}${ctx.acid ? ` and ${ctx.acid}` : ''}.`,
      `Add ${ctx.protein ?? 'protein'} and poach gently until just cooked through — do not boil.`,
      'Remove with a slotted spoon and rest briefly before serving.',
    ],
  },
  {
    id: 'deep-fry',
    name: 'Deep-fried',
    requiredRoles: ['protein', 'fat', 'starch'],
    optionalRoles: ['spice'],
    baseMinutes: 25,
    minutesPerExtraIngredient: 2,
    difficulty: 3,
    healthModifier: 0.55,
    steps: (ctx) => [
      `Heat ${ctx.fat ?? 'oil'} to 350°F (175°C) in a deep, heavy pot.`,
      `Coat ${ctx.protein ?? 'protein'} in a ${ctx.starch ?? 'starch'}-based batter or breading, seasoned with ${ctx.spices.join(', ') || 'seasoning'}.`,
      'Fry in batches until golden and cooked through, then drain on a rack.',
    ],
  },
  {
    id: 'blend',
    name: 'Blended (soup/smoothie)',
    requiredRoles: ['vegetable', 'liquid'],
    optionalRoles: ['dairy', 'protein', 'spice'],
    baseMinutes: 10,
    minutesPerExtraIngredient: 1,
    difficulty: 1,
    healthModifier: 1.1,
    steps: (ctx) => [
      `Combine ${ctx.vegetables.join(', ') || 'vegetables'}${ctx.dairy ? `, ${ctx.dairy}` : ''}${ctx.protein ? `, ${ctx.protein}` : ''} with liquid in a blender.`,
      `Blend until smooth, season with ${ctx.spices.join(', ') || 'seasoning'}.`,
      'Chill or gently warm through, then serve.',
    ],
  },
  {
    id: 'cake',
    name: 'Butter cake (creaming method)',
    requiredRoles: ['flour', 'sweetener', 'fat', 'egg', 'leavening'],
    optionalRoles: ['dairy', 'spice'],
    baseMinutes: 60,
    minutesPerExtraIngredient: 2,
    difficulty: 2,
    healthModifier: 0.6,
    // Unlike savory techniques, baking doesn't tolerate "roughly this much of each role" —
    // ratios below are a standard baker's-percentage butter cake (~250g flour batch),
    // scaled to whichever pantry ingredient fills each role, not to how much of it is on hand.
    steps: (ctx) => [
      `Preheat oven to 350°F (175°C). Grease and flour a cake pan.`,
      `Whisk 250g (2 cups) ${ctx.flour ?? 'flour'} with 10g (about 2 tsp) ${ctx.leavening ?? 'baking powder'} and a pinch of salt.`,
      `Cream 125g ${ctx.fat ?? 'butter'} with 200g ${ctx.sweetener ?? 'sugar'} until light and fluffy, about 3 minutes.`,
      `Beat in 2 ${ctx.egg ?? 'eggs'}, one at a time${ctx.spices.length ? `, then stir in ${ctx.spices.join(', ')}` : ''}.`,
      `Alternate folding in the flour mixture and 65ml ${ctx.dairy ?? 'milk'}, starting and ending with flour, until just combined — do not overmix.`,
      'Pour into the pan and bake until a toothpick comes out clean, 25-35 min. Cool before removing from the pan.',
    ],
  },
  {
    id: 'meringue',
    name: 'Meringue',
    requiredRoles: ['egg-white', 'sweetener'],
    optionalRoles: ['acid', 'spice'],
    baseMinutes: 100,
    minutesPerExtraIngredient: 2,
    difficulty: 2,
    healthModifier: 0.7,
    // Uses only the white half of an egg — buildRecipeForTechnique flags the leftover
    // yolks and, when a yolk-using recipe like custard is also generated, pairs the two.
    steps: (ctx) => [
      'Preheat oven to 200°F (95°C) and line a sheet pan with parchment.',
      `Whip ${ctx.eggWhite ?? 'egg whites'} to soft peaks in a completely clean, grease-free bowl.`,
      ctx.acid
        ? `Add ${ctx.acid} for stability, then whip in 100g ${ctx.sweetener ?? 'sugar'} a spoonful at a time until stiff, glossy peaks form.`
        : `Whip in 100g ${ctx.sweetener ?? 'sugar'} a spoonful at a time until stiff, glossy peaks form.`,
      `Fold in ${ctx.spices.join(', ') || 'flavoring'} if using.`,
      'Pipe or spoon onto the sheet pan and bake low and slow until crisp and dry, 1.5-2 hours. Cool completely before removing.',
    ],
  },
  {
    id: 'custard',
    name: 'Custard',
    requiredRoles: ['egg-yolk', 'dairy', 'sweetener'],
    optionalRoles: ['spice'],
    baseMinutes: 30,
    minutesPerExtraIngredient: 2,
    difficulty: 2,
    healthModifier: 0.55,
    // Uses only the yolk half of an egg — the natural companion to a whites-only meringue.
    steps: (ctx) => [
      `Warm ${ctx.dairy ?? 'milk'} in a saucepan until just steaming, don't boil.`,
      `Whisk ${ctx.eggYolk ?? 'egg yolks'} with 80g ${ctx.sweetener ?? 'sugar'} until pale.`,
      `Slowly pour the warm ${ctx.dairy ?? 'milk'} into the yolks while whisking constantly, to temper them.`,
      `Return to low heat and stir until it coats the back of a spoon — do not let it boil or the eggs will curdle.`,
      `Strain, stir in ${ctx.spices.join(', ') || 'vanilla'}, and chill before serving.`,
    ],
  },
];
